export enum DialogTypes {

    USERS_FETCHED = 'USERS_FETCHED',
    USER_DISCONNECTED = 'USER_DISCONNECTED',
    FETCH_DIALOG = 'FETCH_DIALOG',
    FETCH_DIALOG_SUCCESS = 'FETCH_DIALOG_SUCCESS',
    POST_MESSAGE = 'POST_MESSAGE',
    RECEIVE_MESSAGE = 'RECEIVE_MESSAGE',
}